/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125AuthedRouteImport } from './routes/{-$locale}/_authed'
import { Route as Char123LocaleChar125LogoutRouteImport } from './routes/{-$locale}/logout'
import { Route as Char123LocaleChar125AuthedDashboardIndexRouteImport } from './routes/{-$locale}/_authed/dashboard/index'
import { Route as Char123LocaleChar125AuthedDashboardGroupsIndexRouteImport } from './routes/{-$locale}/_authed/dashboard/groups/index'
import { Route as Char123LocaleChar125AuthedDashboardGroupsGroupIdRouteImport } from './routes/{-$locale}/_authed/dashboard/groups/$groupId'
import { Route as Char123LocaleChar125AuthedDashboardModulesIndexRouteImport } from './routes/{-$locale}/_authed/dashboard/modules/index'
import { Route as Char123LocaleChar125AuthedDashboardModulesModuleIdRouteImport } from './routes/{-$locale}/_authed/dashboard/modules/$moduleId'
import { Route as Char123LocaleChar125AuthedDashboardNodesIndexRouteImport } from './routes/{-$locale}/_authed/dashboard/nodes/index'
import { Route as Char123LocaleChar125AuthedDashboardNodesNodeIdRouteImport } from './routes/{-$locale}/_authed/dashboard/nodes/$nodeId'
import { Route as Char123LocaleChar125AuthedDashboardNodesConfigRouteImport } from './routes/{-$locale}/_authed/dashboard/nodes/config'
import { Route as Char123LocaleChar125AuthedDashboardNodesConsoleRouteImport } from './routes/{-$locale}/_authed/dashboard/nodes/console'
import { Route as Char123LocaleChar125AuthedDashboardPlayersIndexRouteImport } from './routes/{-$locale}/_authed/dashboard/players/index'
import { Route as Char123LocaleChar125AuthedDashboardPlayersPlayerIdRouteImport } from './routes/{-$locale}/_authed/dashboard/players/$playerId'
import { Route as Char123LocaleChar125AuthedDashboardServicesIndexRouteImport } from './routes/{-$locale}/_authed/dashboard/services/index'
import { Route as Char123LocaleChar125AuthedDashboardServicesServiceIdRouteImport } from './routes/{-$locale}/_authed/dashboard/services/$serviceId'
import { Route as Char123LocaleChar125AuthedDashboardServicesCreateRouteImport } from './routes/{-$locale}/_authed/dashboard/services/create'
import { Route as Char123LocaleChar125AuthedDashboardTasksIndexRouteImport } from './routes/{-$locale}/_authed/dashboard/tasks/index'
import { Route as Char123LocaleChar125AuthedDashboardTasksTaskIdRouteImport } from './routes/{-$locale}/_authed/dashboard/tasks/$taskId'
import { Route as Char123LocaleChar125AuthedDashboardTemplatesIndexRouteImport } from './routes/{-$locale}/_authed/dashboard/templates/index'
import { Route as Char123LocaleChar125AuthedDashboardUsersIndexRouteImport } from './routes/{-$locale}/_authed/dashboard/users/index'
import { Route as Char123LocaleChar125AuthedDashboardUsersUserIdRouteImport } from './routes/{-$locale}/_authed/dashboard/users/$userId'
import { Route as Char123LocaleChar125AuthedDashboardVersionsIndexRouteImport } from './routes/{-$locale}/_authed/dashboard/versions/index'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AuthedRoute =
  Char123LocaleChar125AuthedRouteImport.update({
    id: '/_authed',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125LogoutRoute =
  Char123LocaleChar125LogoutRouteImport.update({
    id: '/logout',
    path: '/logout',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AuthedDashboardIndexRoute =
  Char123LocaleChar125AuthedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardGroupsIndexRoute =
  Char123LocaleChar125AuthedDashboardGroupsIndexRouteImport.update({
    id: '/dashboard/groups/',
    path: '/dashboard/groups/',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardGroupsGroupIdRoute =
  Char123LocaleChar125AuthedDashboardGroupsGroupIdRouteImport.update({
    id: '/dashboard/groups/$groupId',
    path: '/dashboard/groups/$groupId',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardModulesIndexRoute =
  Char123LocaleChar125AuthedDashboardModulesIndexRouteImport.update({
    id: '/dashboard/modules/',
    path: '/dashboard/modules/',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardModulesModuleIdRoute =
  Char123LocaleChar125AuthedDashboardModulesModuleIdRouteImport.update({
    id: '/dashboard/modules/$moduleId',
    path: '/dashboard/modules/$moduleId',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardNodesIndexRoute =
  Char123LocaleChar125AuthedDashboardNodesIndexRouteImport.update({
    id: '/dashboard/nodes/',
    path: '/dashboard/nodes/',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardNodesNodeIdRoute =
  Char123LocaleChar125AuthedDashboardNodesNodeIdRouteImport.update({
    id: '/dashboard/nodes/$nodeId',
    path: '/dashboard/nodes/$nodeId',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardNodesConfigRoute =
  Char123LocaleChar125AuthedDashboardNodesConfigRouteImport.update({
    id: '/dashboard/nodes/config',
    path: '/dashboard/nodes/config',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardNodesConsoleRoute =
  Char123LocaleChar125AuthedDashboardNodesConsoleRouteImport.update({
    id: '/dashboard/nodes/console',
    path: '/dashboard/nodes/console',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardPlayersIndexRoute =
  Char123LocaleChar125AuthedDashboardPlayersIndexRouteImport.update({
    id: '/dashboard/players/',
    path: '/dashboard/players/',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardPlayersPlayerIdRoute =
  Char123LocaleChar125AuthedDashboardPlayersPlayerIdRouteImport.update({
    id: '/dashboard/players/$playerId',
    path: '/dashboard/players/$playerId',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardServicesIndexRoute =
  Char123LocaleChar125AuthedDashboardServicesIndexRouteImport.update({
    id: '/dashboard/services/',
    path: '/dashboard/services/',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardServicesServiceIdRoute =
  Char123LocaleChar125AuthedDashboardServicesServiceIdRouteImport.update({
    id: '/dashboard/services/$serviceId',
    path: '/dashboard/services/$serviceId',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardServicesCreateRoute =
  Char123LocaleChar125AuthedDashboardServicesCreateRouteImport.update({
    id: '/dashboard/services/create',
    path: '/dashboard/services/create',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardTasksIndexRoute =
  Char123LocaleChar125AuthedDashboardTasksIndexRouteImport.update({
    id: '/dashboard/tasks/',
    path: '/dashboard/tasks/',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardTasksTaskIdRoute =
  Char123LocaleChar125AuthedDashboardTasksTaskIdRouteImport.update({
    id: '/dashboard/tasks/$taskId',
    path: '/dashboard/tasks/$taskId',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardTemplatesIndexRoute =
  Char123LocaleChar125AuthedDashboardTemplatesIndexRouteImport.update({
    id: '/dashboard/templates/',
    path: '/dashboard/templates/',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardUsersIndexRoute =
  Char123LocaleChar125AuthedDashboardUsersIndexRouteImport.update({
    id: '/dashboard/users/',
    path: '/dashboard/users/',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardUsersUserIdRoute =
  Char123LocaleChar125AuthedDashboardUsersUserIdRouteImport.update({
    id: '/dashboard/users/$userId',
    path: '/dashboard/users/$userId',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)
const Char123LocaleChar125AuthedDashboardVersionsIndexRoute =
  Char123LocaleChar125AuthedDashboardVersionsIndexRouteImport.update({
    id: '/dashboard/versions/',
    path: '/dashboard/versions/',
    getParentRoute: () => Char123LocaleChar125AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/{-$locale}/logout': typeof Char123LocaleChar125LogoutRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/dashboard/': typeof Char123LocaleChar125AuthedDashboardIndexRoute
  '/{-$locale}/dashboard/groups/$groupId': typeof Char123LocaleChar125AuthedDashboardGroupsGroupIdRoute
  '/{-$locale}/dashboard/modules/$moduleId': typeof Char123LocaleChar125AuthedDashboardModulesModuleIdRoute
  '/{-$locale}/dashboard/nodes/$nodeId': typeof Char123LocaleChar125AuthedDashboardNodesNodeIdRoute
  '/{-$locale}/dashboard/nodes/config': typeof Char123LocaleChar125AuthedDashboardNodesConfigRoute
  '/{-$locale}/dashboard/nodes/console': typeof Char123LocaleChar125AuthedDashboardNodesConsoleRoute
  '/{-$locale}/dashboard/players/$playerId': typeof Char123LocaleChar125AuthedDashboardPlayersPlayerIdRoute
  '/{-$locale}/dashboard/services/$serviceId': typeof Char123LocaleChar125AuthedDashboardServicesServiceIdRoute
  '/{-$locale}/dashboard/services/create': typeof Char123LocaleChar125AuthedDashboardServicesCreateRoute
  '/{-$locale}/dashboard/tasks/$taskId': typeof Char123LocaleChar125AuthedDashboardTasksTaskIdRoute
  '/{-$locale}/dashboard/users/$userId': typeof Char123LocaleChar125AuthedDashboardUsersUserIdRoute
  '/{-$locale}/dashboard/groups/': typeof Char123LocaleChar125AuthedDashboardGroupsIndexRoute
  '/{-$locale}/dashboard/modules/': typeof Char123LocaleChar125AuthedDashboardModulesIndexRoute
  '/{-$locale}/dashboard/nodes/': typeof Char123LocaleChar125AuthedDashboardNodesIndexRoute
  '/{-$locale}/dashboard/players/': typeof Char123LocaleChar125AuthedDashboardPlayersIndexRoute
  '/{-$locale}/dashboard/services/': typeof Char123LocaleChar125AuthedDashboardServicesIndexRoute
  '/{-$locale}/dashboard/tasks/': typeof Char123LocaleChar125AuthedDashboardTasksIndexRoute
  '/{-$locale}/dashboard/templates/': typeof Char123LocaleChar125AuthedDashboardTemplatesIndexRoute
  '/{-$locale}/dashboard/users/': typeof Char123LocaleChar125AuthedDashboardUsersIndexRoute
  '/{-$locale}/dashboard/versions/': typeof Char123LocaleChar125AuthedDashboardVersionsIndexRoute
}
export interface FileRoutesByTo {
  '/api/health': typeof ApiHealthRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/logout': typeof Char123LocaleChar125LogoutRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125AuthedDashboardIndexRoute
  '/{-$locale}/dashboard/groups/$groupId': typeof Char123LocaleChar125AuthedDashboardGroupsGroupIdRoute
  '/{-$locale}/dashboard/modules/$moduleId': typeof Char123LocaleChar125AuthedDashboardModulesModuleIdRoute
  '/{-$locale}/dashboard/nodes/$nodeId': typeof Char123LocaleChar125AuthedDashboardNodesNodeIdRoute
  '/{-$locale}/dashboard/nodes/config': typeof Char123LocaleChar125AuthedDashboardNodesConfigRoute
  '/{-$locale}/dashboard/nodes/console': typeof Char123LocaleChar125AuthedDashboardNodesConsoleRoute
  '/{-$locale}/dashboard/players/$playerId': typeof Char123LocaleChar125AuthedDashboardPlayersPlayerIdRoute
  '/{-$locale}/dashboard/services/$serviceId': typeof Char123LocaleChar125AuthedDashboardServicesServiceIdRoute
  '/{-$locale}/dashboard/services/create': typeof Char123LocaleChar125AuthedDashboardServicesCreateRoute
  '/{-$locale}/dashboard/tasks/$taskId': typeof Char123LocaleChar125AuthedDashboardTasksTaskIdRoute
  '/{-$locale}/dashboard/users/$userId': typeof Char123LocaleChar125AuthedDashboardUsersUserIdRoute
  '/{-$locale}/dashboard/groups': typeof Char123LocaleChar125AuthedDashboardGroupsIndexRoute
  '/{-$locale}/dashboard/modules': typeof Char123LocaleChar125AuthedDashboardModulesIndexRoute
  '/{-$locale}/dashboard/nodes': typeof Char123LocaleChar125AuthedDashboardNodesIndexRoute
  '/{-$locale}/dashboard/players': typeof Char123LocaleChar125AuthedDashboardPlayersIndexRoute
  '/{-$locale}/dashboard/services': typeof Char123LocaleChar125AuthedDashboardServicesIndexRoute
  '/{-$locale}/dashboard/tasks': typeof Char123LocaleChar125AuthedDashboardTasksIndexRoute
  '/{-$locale}/dashboard/templates': typeof Char123LocaleChar125AuthedDashboardTemplatesIndexRoute
  '/{-$locale}/dashboard/users': typeof Char123LocaleChar125AuthedDashboardUsersIndexRoute
  '/{-$locale}/dashboard/versions': typeof Char123LocaleChar125AuthedDashboardVersionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/{-$locale}/_authed': typeof Char123LocaleChar125AuthedRouteWithChildren
  '/{-$locale}/logout': typeof Char123LocaleChar125LogoutRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/_authed/dashboard/': typeof Char123LocaleChar125AuthedDashboardIndexRoute
  '/{-$locale}/_authed/dashboard/groups/$groupId': typeof Char123LocaleChar125AuthedDashboardGroupsGroupIdRoute
  '/{-$locale}/_authed/dashboard/modules/$moduleId': typeof Char123LocaleChar125AuthedDashboardModulesModuleIdRoute
  '/{-$locale}/_authed/dashboard/nodes/$nodeId': typeof Char123LocaleChar125AuthedDashboardNodesNodeIdRoute
  '/{-$locale}/_authed/dashboard/nodes/config': typeof Char123LocaleChar125AuthedDashboardNodesConfigRoute
  '/{-$locale}/_authed/dashboard/nodes/console': typeof Char123LocaleChar125AuthedDashboardNodesConsoleRoute
  '/{-$locale}/_authed/dashboard/players/$playerId': typeof Char123LocaleChar125AuthedDashboardPlayersPlayerIdRoute
  '/{-$locale}/_authed/dashboard/services/$serviceId': typeof Char123LocaleChar125AuthedDashboardServicesServiceIdRoute
  '/{-$locale}/_authed/dashboard/services/create': typeof Char123LocaleChar125AuthedDashboardServicesCreateRoute
  '/{-$locale}/_authed/dashboard/tasks/$taskId': typeof Char123LocaleChar125AuthedDashboardTasksTaskIdRoute
  '/{-$locale}/_authed/dashboard/users/$userId': typeof Char123LocaleChar125AuthedDashboardUsersUserIdRoute
  '/{-$locale}/_authed/dashboard/groups/': typeof Char123LocaleChar125AuthedDashboardGroupsIndexRoute
  '/{-$locale}/_authed/dashboard/modules/': typeof Char123LocaleChar125AuthedDashboardModulesIndexRoute
  '/{-$locale}/_authed/dashboard/nodes/': typeof Char123LocaleChar125AuthedDashboardNodesIndexRoute
  '/{-$locale}/_authed/dashboard/players/': typeof Char123LocaleChar125AuthedDashboardPlayersIndexRoute
  '/{-$locale}/_authed/dashboard/services/': typeof Char123LocaleChar125AuthedDashboardServicesIndexRoute
  '/{-$locale}/_authed/dashboard/tasks/': typeof Char123LocaleChar125AuthedDashboardTasksIndexRoute
  '/{-$locale}/_authed/dashboard/templates/': typeof Char123LocaleChar125AuthedDashboardTemplatesIndexRoute
  '/{-$locale}/_authed/dashboard/users/': typeof Char123LocaleChar125AuthedDashboardUsersIndexRoute
  '/{-$locale}/_authed/dashboard/versions/': typeof Char123LocaleChar125AuthedDashboardVersionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/api/health'
    | '/{-$locale}/logout'
    | '/{-$locale}/'
    | '/{-$locale}/dashboard/'
    | '/{-$locale}/dashboard/groups/$groupId'
    | '/{-$locale}/dashboard/modules/$moduleId'
    | '/{-$locale}/dashboard/nodes/$nodeId'
    | '/{-$locale}/dashboard/nodes/config'
    | '/{-$locale}/dashboard/nodes/console'
    | '/{-$locale}/dashboard/players/$playerId'
    | '/{-$locale}/dashboard/services/$serviceId'
    | '/{-$locale}/dashboard/services/create'
    | '/{-$locale}/dashboard/tasks/$taskId'
    | '/{-$locale}/dashboard/users/$userId'
    | '/{-$locale}/dashboard/groups/'
    | '/{-$locale}/dashboard/modules/'
    | '/{-$locale}/dashboard/nodes/'
    | '/{-$locale}/dashboard/players/'
    | '/{-$locale}/dashboard/services/'
    | '/{-$locale}/dashboard/tasks/'
    | '/{-$locale}/dashboard/templates/'
    | '/{-$locale}/dashboard/users/'
    | '/{-$locale}/dashboard/versions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/health'
    | '/{-$locale}'
    | '/{-$locale}/logout'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/dashboard/groups/$groupId'
    | '/{-$locale}/dashboard/modules/$moduleId'
    | '/{-$locale}/dashboard/nodes/$nodeId'
    | '/{-$locale}/dashboard/nodes/config'
    | '/{-$locale}/dashboard/nodes/console'
    | '/{-$locale}/dashboard/players/$playerId'
    | '/{-$locale}/dashboard/services/$serviceId'
    | '/{-$locale}/dashboard/services/create'
    | '/{-$locale}/dashboard/tasks/$taskId'
    | '/{-$locale}/dashboard/users/$userId'
    | '/{-$locale}/dashboard/groups'
    | '/{-$locale}/dashboard/modules'
    | '/{-$locale}/dashboard/nodes'
    | '/{-$locale}/dashboard/players'
    | '/{-$locale}/dashboard/services'
    | '/{-$locale}/dashboard/tasks'
    | '/{-$locale}/dashboard/templates'
    | '/{-$locale}/dashboard/users'
    | '/{-$locale}/dashboard/versions'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/api/health'
    | '/{-$locale}/_authed'
    | '/{-$locale}/logout'
    | '/{-$locale}/'
    | '/{-$locale}/_authed/dashboard/'
    | '/{-$locale}/_authed/dashboard/groups/$groupId'
    | '/{-$locale}/_authed/dashboard/modules/$moduleId'
    | '/{-$locale}/_authed/dashboard/nodes/$nodeId'
    | '/{-$locale}/_authed/dashboard/nodes/config'
    | '/{-$locale}/_authed/dashboard/nodes/console'
    | '/{-$locale}/_authed/dashboard/players/$playerId'
    | '/{-$locale}/_authed/dashboard/services/$serviceId'
    | '/{-$locale}/_authed/dashboard/services/create'
    | '/{-$locale}/_authed/dashboard/tasks/$taskId'
    | '/{-$locale}/_authed/dashboard/users/$userId'
    | '/{-$locale}/_authed/dashboard/groups/'
    | '/{-$locale}/_authed/dashboard/modules/'
    | '/{-$locale}/_authed/dashboard/nodes/'
    | '/{-$locale}/_authed/dashboard/players/'
    | '/{-$locale}/_authed/dashboard/services/'
    | '/{-$locale}/_authed/dashboard/tasks/'
    | '/{-$locale}/_authed/dashboard/templates/'
    | '/{-$locale}/_authed/dashboard/users/'
    | '/{-$locale}/_authed/dashboard/versions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/_authed': {
      id: '/{-$locale}/_authed'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125AuthedRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/logout': {
      id: '/{-$locale}/logout'
      path: '/logout'
      fullPath: '/{-$locale}/logout'
      preLoaderRoute: typeof Char123LocaleChar125LogoutRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/_authed/dashboard/': {
      id: '/{-$locale}/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/{-$locale}/dashboard/'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/groups/': {
      id: '/{-$locale}/_authed/dashboard/groups/'
      path: '/dashboard/groups'
      fullPath: '/{-$locale}/dashboard/groups/'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardGroupsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/groups/$groupId': {
      id: '/{-$locale}/_authed/dashboard/groups/$groupId'
      path: '/dashboard/groups/$groupId'
      fullPath: '/{-$locale}/dashboard/groups/$groupId'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardGroupsGroupIdRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/modules/': {
      id: '/{-$locale}/_authed/dashboard/modules/'
      path: '/dashboard/modules'
      fullPath: '/{-$locale}/dashboard/modules/'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardModulesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/modules/$moduleId': {
      id: '/{-$locale}/_authed/dashboard/modules/$moduleId'
      path: '/dashboard/modules/$moduleId'
      fullPath: '/{-$locale}/dashboard/modules/$moduleId'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardModulesModuleIdRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/nodes/': {
      id: '/{-$locale}/_authed/dashboard/nodes/'
      path: '/dashboard/nodes'
      fullPath: '/{-$locale}/dashboard/nodes/'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardNodesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/nodes/$nodeId': {
      id: '/{-$locale}/_authed/dashboard/nodes/$nodeId'
      path: '/dashboard/nodes/$nodeId'
      fullPath: '/{-$locale}/dashboard/nodes/$nodeId'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardNodesNodeIdRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/nodes/config': {
      id: '/{-$locale}/_authed/dashboard/nodes/config'
      path: '/dashboard/nodes/config'
      fullPath: '/{-$locale}/dashboard/nodes/config'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardNodesConfigRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/nodes/console': {
      id: '/{-$locale}/_authed/dashboard/nodes/console'
      path: '/dashboard/nodes/console'
      fullPath: '/{-$locale}/dashboard/nodes/console'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardNodesConsoleRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/players/': {
      id: '/{-$locale}/_authed/dashboard/players/'
      path: '/dashboard/players'
      fullPath: '/{-$locale}/dashboard/players/'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardPlayersIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/players/$playerId': {
      id: '/{-$locale}/_authed/dashboard/players/$playerId'
      path: '/dashboard/players/$playerId'
      fullPath: '/{-$locale}/dashboard/players/$playerId'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardPlayersPlayerIdRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/services/': {
      id: '/{-$locale}/_authed/dashboard/services/'
      path: '/dashboard/services'
      fullPath: '/{-$locale}/dashboard/services/'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardServicesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/services/$serviceId': {
      id: '/{-$locale}/_authed/dashboard/services/$serviceId'
      path: '/dashboard/services/$serviceId'
      fullPath: '/{-$locale}/dashboard/services/$serviceId'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardServicesServiceIdRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/services/create': {
      id: '/{-$locale}/_authed/dashboard/services/create'
      path: '/dashboard/services/create'
      fullPath: '/{-$locale}/dashboard/services/create'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardServicesCreateRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/tasks/': {
      id: '/{-$locale}/_authed/dashboard/tasks/'
      path: '/dashboard/tasks'
      fullPath: '/{-$locale}/dashboard/tasks/'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardTasksIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/tasks/$taskId': {
      id: '/{-$locale}/_authed/dashboard/tasks/$taskId'
      path: '/dashboard/tasks/$taskId'
      fullPath: '/{-$locale}/dashboard/tasks/$taskId'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardTasksTaskIdRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/templates/': {
      id: '/{-$locale}/_authed/dashboard/templates/'
      path: '/dashboard/templates'
      fullPath: '/{-$locale}/dashboard/templates/'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardTemplatesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/users/': {
      id: '/{-$locale}/_authed/dashboard/users/'
      path: '/dashboard/users'
      fullPath: '/{-$locale}/dashboard/users/'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardUsersIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/users/$userId': {
      id: '/{-$locale}/_authed/dashboard/users/$userId'
      path: '/dashboard/users/$userId'
      fullPath: '/{-$locale}/dashboard/users/$userId'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardUsersUserIdRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
    '/{-$locale}/_authed/dashboard/versions/': {
      id: '/{-$locale}/_authed/dashboard/versions/'
      path: '/dashboard/versions'
      fullPath: '/{-$locale}/dashboard/versions/'
      preLoaderRoute: typeof Char123LocaleChar125AuthedDashboardVersionsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthedRoute
    }
  }
}

interface Char123LocaleChar125AuthedRouteChildren {
  Char123LocaleChar125AuthedDashboardIndexRoute: typeof Char123LocaleChar125AuthedDashboardIndexRoute
  Char123LocaleChar125AuthedDashboardGroupsGroupIdRoute: typeof Char123LocaleChar125AuthedDashboardGroupsGroupIdRoute
  Char123LocaleChar125AuthedDashboardModulesModuleIdRoute: typeof Char123LocaleChar125AuthedDashboardModulesModuleIdRoute
  Char123LocaleChar125AuthedDashboardNodesNodeIdRoute: typeof Char123LocaleChar125AuthedDashboardNodesNodeIdRoute
  Char123LocaleChar125AuthedDashboardNodesConfigRoute: typeof Char123LocaleChar125AuthedDashboardNodesConfigRoute
  Char123LocaleChar125AuthedDashboardNodesConsoleRoute: typeof Char123LocaleChar125AuthedDashboardNodesConsoleRoute
  Char123LocaleChar125AuthedDashboardPlayersPlayerIdRoute: typeof Char123LocaleChar125AuthedDashboardPlayersPlayerIdRoute
  Char123LocaleChar125AuthedDashboardServicesServiceIdRoute: typeof Char123LocaleChar125AuthedDashboardServicesServiceIdRoute
  Char123LocaleChar125AuthedDashboardServicesCreateRoute: typeof Char123LocaleChar125AuthedDashboardServicesCreateRoute
  Char123LocaleChar125AuthedDashboardTasksTaskIdRoute: typeof Char123LocaleChar125AuthedDashboardTasksTaskIdRoute
  Char123LocaleChar125AuthedDashboardUsersUserIdRoute: typeof Char123LocaleChar125AuthedDashboardUsersUserIdRoute
  Char123LocaleChar125AuthedDashboardGroupsIndexRoute: typeof Char123LocaleChar125AuthedDashboardGroupsIndexRoute
  Char123LocaleChar125AuthedDashboardModulesIndexRoute: typeof Char123LocaleChar125AuthedDashboardModulesIndexRoute
  Char123LocaleChar125AuthedDashboardNodesIndexRoute: typeof Char123LocaleChar125AuthedDashboardNodesIndexRoute
  Char123LocaleChar125AuthedDashboardPlayersIndexRoute: typeof Char123LocaleChar125AuthedDashboardPlayersIndexRoute
  Char123LocaleChar125AuthedDashboardServicesIndexRoute: typeof Char123LocaleChar125AuthedDashboardServicesIndexRoute
  Char123LocaleChar125AuthedDashboardTasksIndexRoute: typeof Char123LocaleChar125AuthedDashboardTasksIndexRoute
  Char123LocaleChar125AuthedDashboardTemplatesIndexRoute: typeof Char123LocaleChar125AuthedDashboardTemplatesIndexRoute
  Char123LocaleChar125AuthedDashboardUsersIndexRoute: typeof Char123LocaleChar125AuthedDashboardUsersIndexRoute
  Char123LocaleChar125AuthedDashboardVersionsIndexRoute: typeof Char123LocaleChar125AuthedDashboardVersionsIndexRoute
}

const Char123LocaleChar125AuthedRouteChildren: Char123LocaleChar125AuthedRouteChildren =
  {
    Char123LocaleChar125AuthedDashboardIndexRoute:
      Char123LocaleChar125AuthedDashboardIndexRoute,
    Char123LocaleChar125AuthedDashboardGroupsGroupIdRoute:
      Char123LocaleChar125AuthedDashboardGroupsGroupIdRoute,
    Char123LocaleChar125AuthedDashboardModulesModuleIdRoute:
      Char123LocaleChar125AuthedDashboardModulesModuleIdRoute,
    Char123LocaleChar125AuthedDashboardNodesNodeIdRoute:
      Char123LocaleChar125AuthedDashboardNodesNodeIdRoute,
    Char123LocaleChar125AuthedDashboardNodesConfigRoute:
      Char123LocaleChar125AuthedDashboardNodesConfigRoute,
    Char123LocaleChar125AuthedDashboardNodesConsoleRoute:
      Char123LocaleChar125AuthedDashboardNodesConsoleRoute,
    Char123LocaleChar125AuthedDashboardPlayersPlayerIdRoute:
      Char123LocaleChar125AuthedDashboardPlayersPlayerIdRoute,
    Char123LocaleChar125AuthedDashboardServicesServiceIdRoute:
      Char123LocaleChar125AuthedDashboardServicesServiceIdRoute,
    Char123LocaleChar125AuthedDashboardServicesCreateRoute:
      Char123LocaleChar125AuthedDashboardServicesCreateRoute,
    Char123LocaleChar125AuthedDashboardTasksTaskIdRoute:
      Char123LocaleChar125AuthedDashboardTasksTaskIdRoute,
    Char123LocaleChar125AuthedDashboardUsersUserIdRoute:
      Char123LocaleChar125AuthedDashboardUsersUserIdRoute,
    Char123LocaleChar125AuthedDashboardGroupsIndexRoute:
      Char123LocaleChar125AuthedDashboardGroupsIndexRoute,
    Char123LocaleChar125AuthedDashboardModulesIndexRoute:
      Char123LocaleChar125AuthedDashboardModulesIndexRoute,
    Char123LocaleChar125AuthedDashboardNodesIndexRoute:
      Char123LocaleChar125AuthedDashboardNodesIndexRoute,
    Char123LocaleChar125AuthedDashboardPlayersIndexRoute:
      Char123LocaleChar125AuthedDashboardPlayersIndexRoute,
    Char123LocaleChar125AuthedDashboardServicesIndexRoute:
      Char123LocaleChar125AuthedDashboardServicesIndexRoute,
    Char123LocaleChar125AuthedDashboardTasksIndexRoute:
      Char123LocaleChar125AuthedDashboardTasksIndexRoute,
    Char123LocaleChar125AuthedDashboardTemplatesIndexRoute:
      Char123LocaleChar125AuthedDashboardTemplatesIndexRoute,
    Char123LocaleChar125AuthedDashboardUsersIndexRoute:
      Char123LocaleChar125AuthedDashboardUsersIndexRoute,
    Char123LocaleChar125AuthedDashboardVersionsIndexRoute:
      Char123LocaleChar125AuthedDashboardVersionsIndexRoute,
  }

const Char123LocaleChar125AuthedRouteWithChildren =
  Char123LocaleChar125AuthedRoute._addFileChildren(
    Char123LocaleChar125AuthedRouteChildren,
  )

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125AuthedRoute: typeof Char123LocaleChar125AuthedRouteWithChildren
  Char123LocaleChar125LogoutRoute: typeof Char123LocaleChar125LogoutRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125AuthedRoute: Char123LocaleChar125AuthedRouteWithChildren,
  Char123LocaleChar125LogoutRoute: Char123LocaleChar125LogoutRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
